name: jescore deployment system

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  test-on-remote-agents:
    name: Physical MCU unit test
    runs-on: rpi-cm5-1
    environment:
      name: hardware-test
    strategy:
      matrix:
        test-config: [
          { env: 'az-delivery-devkit-v4-test-arduino', platform: 'esp32', usb_port: '/dev/ttyUSB0' },
          { env: 'stm32_h753zi-test-cube', platform: 'stm32', usb_port: '/dev/ttyACM0' }
        ]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if agent is available and run tests
        env:
          TEST_ENV: ${{ matrix.test-config.env }}
          PLATFORM: ${{ matrix.test-config.platform }}
          USB_PORT: ${{ matrix.test-config.usb_port }}
        run: |
          echo "Running tests with environment $TEST_ENV (USB: $USB_PORT)..."
          pio test -e "$TEST_ENV" --upload-port "$USB_PORT" --test-port "$USB_PORT"

